### PR TITLE
Update SweatAlert2 package with 2021 specifications

### PR DESCRIPTION
**Pull request by chantastic**
Update sweetalert2 wrapper package to support v10
    
Updates @planningcenter/sweetalert2 package to wrap v10 of sweetalert2.
Documentation has been dramatically improved.
    
This was a collaboration with @chantastic and @hufort and represents 32 commits over about 1 1/2 work weeks.
    
These are the highlight tasks completed:
    
Tasks:
* [x] Improve documentation with pairing notes
  * [x] Add note on `.css` syntax and Sass `@import` directive
  * [x] Fix typos and syntax highlighting in code snippets
  * [x] Add further reading resources and installations
  * [x] Add note on importing from the nested path to bypass Stylesheet injection
  * [x] Add comments to code for further clarification of examples
* [x] Update exported styles to match 2021 specification
  * [x] Updating intra-element padding
  * [x] Remove extraneous margin from buttons
  * [x] Verify font weights and sizes
  * [x] Implement icons technique established in Publishing?
  * [x] Implement property objects for standard, alternate messaging?
* [x] Update to v10 API of SweetAlert
* [x] Polish and documentation
  * [x] change button approach back to four-edge margin to support mobile
  * [x] update codesandbox
  * [x] provide documentation for creating a convenient localized API with reasons why it doesn't belong in library code
  * [x] update example sandboxes
  * [x] mirror readme documentation in storybook

## Updated CodeSandbox installation guides

Basic setup: https://codesandbox.io/s/planningcentersweetalert2-swal-v10-9qvwr

Creating a local library wrapper to reduce duplication: https://codesandbox.io/s/planningcentersweetalert2-swal-v10-0qx9i?file=/src/alerts.js

#### `standard alert`

Screen Shot 2021-02-16 at 2 44 30 PM

#### `success alert`

Screen Shot 2021-02-16 at 2 44 25 PM

#### `error alert`

Screen Shot 2021-02-16 at 2 44 21 PM

#### `standard confirm`

Screen Shot 2021-02-16 at 2 44 17 PM

#### `create confirm`

Screen Shot 2021-02-16 at 2 44 12 PM

#### `destroy confirm`

Screen Shot 2021-02-16 at 2 44 07 PM

#### Legacy is still in tact

Screen Shot 2021-02-16 at 2 44 00 PM

This is important for large apps that want to do a staged migration

#### Mobile

Screen Shot 2021-02-16 at 2 44 54 PM

### CODE REVIEW

**Comment by chantastic** [comment]
@hufort, thanks for reaching out today. I'm excited to work with you to make sure that your installation of `@planningcenter/sweetalert2` matches the style specified by the R&F team last year and implemented during the Unity project last month.

We'll need to make updates to either the library *or* Services. If you're available, I think this is something we could explore together and update this library for all consumers.

**Comment by hufort** [comment]
Thanks for the quick help. Looking forward to working on this.

**Comment by chantastic** [comment]
Status Update, regarding 8f13720

image

    Setup crude dev env and add v10 variables
    
    Adds a crude working environment by copy/pasting static output from the
    example CodeSandbox.
    
    Later we'll add further (static) stories for testing.
    
    This also updates replaces the existing stylesheet with one compatable
    with the v10 Sass variables.
    
    Many more customization points were added.
    
    This isn't complete. Icon size and color still need to be addressed. And
    more examples added for possible variants. But the sizing is mostly
    correct.

**Comment by chantastic** [comment]
worth noting for next week:

the team that specified this made the decision that colors should not be configurable. so, we won't need to continue exposing customization variables. (at least not until that decision needs to be revisited)

**Comment by chantastic** [comment]
Big Diff Energy this morning with Visual Test harness setup and examples drawn from Figma Spec.

image

The examples are all doubled to account for deficiencies in the way we utilize the library.

To maintain visual regression testability, I've added static examples near to their dynamic counterparts. Worth noting that this *only* tests for visual regressions of previous "exported" examples. It doesn't update with examples. Nor does it test anything related to the JS API.

(_Previously "exported"_: trigger example, open in inspector, copy/paste HTHML, convert to JSX, paste.)

Also included is a diff that updates the `peerDependencies` statement to `>=10`

**Comment by chantastic** [comment]
@hufort thanks for continuing to update this document!

In light of our conversation yesterday, I took the liberty of creating a new outline (at the bottom of the readme).
I'm not married to any one part of it but thought it might provide a nice backbone for the documentation — as we planned it.

The one area that I fleshed out was a section of implementing a facade.
Some products use a translucent facade — which was previously [PR'd here](https://github.com/planningcenter/design/pull/13).
As stated there and in the related [basecamp thread](https://3.basecamp.com/3670704/buckets/4998590/messages/2248307448), I see transparent facades as a dangerous pattern — a problem that's exacerbated exponentially when stuffed into a library.
I tried to summarize reasons for and against in that `Implementing a facade` section.

**Pull request merged**
