### PR TITLE
add 8px margin between name and profile links in menu

### PR DESCRIPTION
**Pull request by souporserious**
Fixes no spacing in between name and profile links.

### CODE REVIEW

**Comment by souporserious** [comment]
[Update base font to system-ui stack](https://trello.com/c/xNgbxpEO/10819-update-base-font-to-system-ui-stack)

**Comment by chantastic** [comment]
Looks good. I merged in `master` to get the "em -> px" fix.
If it still looks good to you, let's merge it.

**Comment by souporserious** [comment]
Sweet, looks good on my end 👍. Thanks for getting the releases out so quick 🙏.

**Comment by chantastic** [comment]
stellar ✨

released as `4.0.2`.
thanks again for the fix 👊

**Pull request merged**
