### PR TITLE
chore: extract @planningcenter/system from monorepo

### PR DESCRIPTION
**Pull request by geolessel**
Its new home is [planningcenter/system](https://github.com/planningcenter/system)

### CODE REVIEW

**Review by dsecrest — APPROVED** [review]

**Comment by geolessel** [comment]
[Extract repos from the design monorepo](https://trello.com/c/SmJxV5TW/15-extract-repos-from-the-design-monorepo)

**Comment by joshwilkerson** [comment]
@geolessel this packages seems _very_ WIP... are there any products using it?

**Review by joshwilkerson — APPROVED** [review]
🤷‍♂️ 😆

**Comment by geolessel** [comment]
> @geolessel this package seems _very_ WIP... are there any products using it?

Yeah, but few enough that it is worth questioning its existence. From my quick searching, it looks like:

- [church-center](https://github.com/ministrycentered/church-center/blob/de88f069f37d77e1bbe0d7ac682af4b39a778d8d/app/javascript/source/calendar/list/EventListing.jsx#L8) (in a few other places as well)
- [publishing](https://github.com/ministrycentered/publishing/blob/a1395102b83938df07e74d9cb080bfa21bb57ffb/package.json#L31) imports it but I don't see it used

**Comment by dsecrest** [comment]
Not only is it very WIP, I'm not sure anyone really has a handle on what it's doing. I say, if we can get rid of it, lez do it.

**Pull request merged**
