### PR TITLE
Fix list formatting bug

### PR DESCRIPTION
**Pull request by dsecrest**
Nested ordered and unordered lists should not have bottom margins.

### CODE REVIEW

**Comment by geolessel** [comment]
@dsecrest is there a reason this PR adds a new tag/version to `topbar`? I don't see any relevant changes as it looks like a churchcenter change, but am unfamiliar with `preformatted-content`.

**Comment by dsecrest** [comment]
Yeah. This is the whole issue with lerna and all of this in the monorepo. It wants to publish new versions when it thinks there are changes. I’m not sure what those changes would be 🤷🏼‍♂️

**Comment by dsecrest** [comment]
@geolessel where are we with this? This is a simple fix that is needed for CCW, but it's not critical. Is this a case where we need to split the repo out from design so that we aren't affecting versions of other projects in the repo? or can this be shipped?

**Comment by geolessel** [comment]
@dsecrest go ahead and ship it. I've effectively already split out topbar (see https://github.com/ministrycentered/topbar and https://github.com/planningcenter/design/pull/147) so tagging topbar won't really have a practical effect anymore.

**Review by geolessel — APPROVED** [review]

**Pull request merged**
